name: 'Download translations'
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SimpleLocalize Download
        uses: simplelocalize/download@2.0
        with:
          apiKey: MY_API_KEY
          downloadPath: ./locales/{ns}/messages-{lang}.json
          downloadFormat: single-language-json
