name: Simple CI Pipeline
run-name: Simple Example
# Triggers the workflow on push events to the 'main' branch
on:
  push:
    branches:
      - main

# Define jobs to run
jobs:
  build:
    # Choose the runner environment
    runs-on: ubuntu-latest

    # Steps define the sequence of commands
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      

      # Step 5: Echo a message (optional)
      - name: Display success message
        run: echo "CI Pipeline executed successfully!"

  protoc-setup:
    uses: ./.github/workflows/protoc-msg.yml  # Reusable workflow ko yahan use karenge
    with:
      runner: ubuntu-latest  # Input denge jo protoc-msg.yml maangega
    permissions:   # Reusable workflow ke liye yeh line add karna zaroori hai
      id-token: write
      contents: read     
