name: 'Upload translations'
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SimpleLocalize Upload
        uses: simplelocalize/upload@2.0
        with:
          apiKey: <MY_API_TOKEN>
          uploadPath: ./locales/{ns}/messages-{lang}.json
          uploadFormat: single-language-json
