name: 'Upload translations'
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SimpleLocalize Upload
        uses: simplelocalize/upload@1.0.0
        with:
          apiKey: Fb833361435A6d2A4E226f439EA7974bEFba7D3E69E29912cf928aB93f435A69
          uploadPath: ./input-sample.json
          uploadFormat: multi-language-json
